appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: G0LTaUwpq7RofZnSkfBsJ12lY68aDdxJE+KvKVoEu/0+AJsSq1YvL//NML7Mxbxb/6NaQdyfVHsTQf+ixxg1wTEj5wvegPJ2vJolKgYnpT3pu+ApRkhray3BxrtAGKe65jA+uilMnFJAN59b6QLZUoCOWzYGg/aEU30Gg9IZlokskd7o1/Mv9MQSx1gMm+z60IANeuK1/2fVTl/k+KN8Cre2smBvVp0mQ43Ethj0vzme//q6T4c5m6E9JoAI01yxUnqim3xZ4bupgeDN4cJyjO9Zll4Q2AwzZOnp1Q9pcbzWgFfZSnphv6iLVs6yJ0wqveuQ/yGkVNGqqrF5EF/gHepQxu29EmlpTs7yAhub+BUFagtHlbXAb50UW1R5o33kiMOP1jLZfadT1nwOLJW2lBdUWIGqsjWBabuO+uSViKjQfPTHxtBweBryb/c+jJ8WkwjQflf0O049iIb1/UcYvKUBWjo6yb/gQ4Bji1usIZTd/2l5YPSy2RuQryIiQLI2NaRaB4U8Etq7O4EHtTKG7P9QpTl08lE8ws+MNn+59rzTWQMPXbCJwVKHf3Gjy1TdvuzqFlOG76uxi+1AqyCZe+TmPs1UmYiSqXL6J5eXsKEI5oO3mwXe/dOeu4J8nTKBkOEst0GNHDNLprbAerzSDFxhdcN3Yvl1ne/ibMwyUWw=
conda_forge_output_validation: true
